INSTALL_TARGET_PROCESSES = SpringBoard

ARCHS = armv7 arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GoogleMapsStatusBarETA

GoogleMapsStatusBarETA_FILES = Tweak.xm
GoogleMapsStatusBarETA_FRAMEWORKS = UIKit
GoogleMapsStatusBarETA_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
